-- 1. Crear tabla de láminas maestras
CREATE TABLE IF NOT EXISTS public.stickers (
    id TEXT PRIMARY KEY,
    section TEXT NOT NULL,
    type TEXT NOT NULL,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Crear tabla de perfiles de usuario
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    full_name TEXT,
    avatar_url TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Crear tabla de inventario del usuario
CREATE TABLE IF NOT EXISTS public.user_stickers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    sticker_id TEXT REFERENCES public.stickers(id) ON DELETE CASCADE NOT NULL,
    quantity INTEGER DEFAULT 0 CHECK (quantity >= 0),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, sticker_id)
);

-- 4. Habilitar RLS (Row Level Security)
ALTER TABLE public.stickers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_stickers ENABLE ROW LEVEL SECURITY;

-- 5. Reglas de Seguridad
-- Stickers: Lectura pública
CREATE POLICY "Public stickers are readable by everyone" ON public.stickers
    FOR SELECT USING (true);

-- Profiles: Cada usuario puede leer y editar solo su perfil
CREATE POLICY "Users can view own profile" ON public.profiles
    FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles
    FOR UPDATE USING (auth.uid() = id);

-- User Stickers: Cada usuario gestiona sus propias láminas
CREATE POLICY "Users can view own stickers" ON public.user_stickers
    FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own stickers" ON public.user_stickers
    FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own stickers" ON public.user_stickers
    FOR UPDATE USING (auth.uid() = user_id);

-- Trigger para crear perfil automáticamente al registrarse
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, avatar_url)
  VALUES (NEW.id, NEW.email, NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'avatar_url');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
